version: "3"
services:
  server:
    build:
      context: ./server
    ports:
      - "8080:8080"
    networks:
      - app_net
    depends_on:
      - mysql
  client:
    build:
      context: ./client
    networks:
      - app_net
    depends_on:
      - server
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    networks:
      - app_net
networks:
  app_net:
    driver: bridge
